name: Manual iOS Build for Flet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Flet
      run: pip install flet

    - name: Install Xcode Command Line Tools
      run: |
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -license accept

    - name: Build iOS IPA
      run: flet build ipa

    - name: Check IPA files
      run: ls -R build/ios/archive

    - name: Create IPA manually if missing
      run: |
        if [ ! -f build/ipa/*.ipa ]; then
          echo "IPA file not found, creating manually..."
          
          # Проверяем правильный путь к Runner.app
          APP_PATH="build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app"
          
          if [ -d "$APP_PATH" ]; then
            mkdir -p build/ipa/Payload
            cp -r "$APP_PATH" build/ipa/Payload/
            cd build/ipa
            zip -r Runner.ipa Payload/
          else
            echo "ERROR: Runner.app not found at $APP_PATH"
            exit 1
          fi
        else
          echo "IPA file exists, skipping manual creation."
        fi

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: flet-app-ipa
        path: build/ipa/*.ipa