name: Build iOS App

on:
  workflow_dispatch:  # Запуск вручную
  push:
    branches:
      - main  # Запуск при пуше в main

jobs:
  build-ios:
    runs-on: macos-latest  # GitHub использует macOS для сборки

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python and dependencies
        run: |
          brew install python
          pip install flet

      - name: Install Xcode and dependencies
        run: |
          xcode-select --install
          sudo gem install cocoapods
          pod install

      - name: Build iOS app
        run: |
          flet build ios

      - name: Find app name dynamically
        id: find_app
        run: |
          APP_NAME=$(ls build/ios | grep .xcarchive | sed 's/.xcarchive//')
          echo "App name found: $APP_NAME"
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV

      - name: Export IPA file
        run: |
          xcodebuild -exportArchive \
            -archivePath "build/ios/$APP_NAME.xcarchive" \
            -exportPath "build/ios/$APP_NAME.ipa" \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flet-ios-app
          path: build/ios/*.ipa
