name: Manual iOS Build for Flet

on:
  workflow_dispatch:  # Ручной запуск по кнопке

jobs:
  build:
    runs-on: macos-latest  # macOS runner для сборки iOS-приложений

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Flet
      run: pip install flet

    - name: Install Xcode Command Line Tools
      run: |
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -license accept

    - name: Build iOS
      run: flet build ipa  # Твоя команда для билда iOS

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: flet-app-ipa
        path: build/ipa  # Путь к файлу .ipa для iOS