name: Build iOS App

on:
  workflow_dispatch:  # Это позволяет запускать билд вручную через GitHub Actions UI

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo gem install cocoapods
        pod install

    - name: Check ExportOptions.plist
      run: ls -la ExportOptions.plist

    - name: Build and Archive iOS App
      run: |
        xcodebuild -workspace YourProject.xcworkspace \
          -scheme YourScheme \
          -sdk iphoneos \
          -configuration Release \
          -archivePath build/ios/YourApp.xcarchive \
          archive

    - name: Export IPA file
      run: |
        xcodebuild -exportArchive \
          -archivePath "build/ios/YourApp.xcarchive" \
          -exportPath "build/ios/" \
          -exportOptionsPlist ExportOptions.plist

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ios-app-ipa
        path: build/ios/*.ipa