name: Manual EXE Build for Flet

on:
  workflow_dispatch:  # Ручной запуск по кнопке

jobs:
  build:
    runs-on: windows-latest  # Используем Windows для сборки .exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Set code page to UTF-8
      run: |
        $OutputEncoding = [System.Text.Encoding]::UTF8

    - name: Install Flet
      run: pip install flet

    - name: Check Python version
      run: python --version

    - name: Check Flet version
      run: pip show flet

    - name: Build EXE
      run: flet build windows --no-ansi

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: flet-app
        path: build/windows/**/*.exe  # Замените на фактический путь к вашему .exe файлу