name: Manual APK Build for Flet

on:
  workflow_dispatch:  # Это делает процесс ручным, его можно запускать кнопкой

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Можно изменить на нужную версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet

    - name: Build APK
      run: |
        flet build apk  # Команда для сборки APK

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: flet-app-apk
        path: ./build/*.apk  # Путь к скомпилированному файлу APK
